# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [3]:
pip install pandas

Requirement already satisfied: pandas in d:\arxius\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\arxius\anaconda\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\arxius\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\arxius\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\arxius\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\arxius\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
import pandas as pd
df = pd.read_csv(url)

In [3]:
df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [25]:
df.shape

(4008, 11)

In [4]:
print(df.columns)

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [6]:
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

In [7]:
df.rename(columns={'GENDER': 'Gender', 'ST': 'State'}, inplace=True)

In [15]:
print(df.columns.tolist())

['customer', 'State', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']

In [20]:
df.rename(columns={'State': 'state'}, inplace=True)

In [21]:
df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [23]:
# Your code here
columnes_check = ['gender', 'state', 'education', 'vehicle_class', 'customer_lifetime_value']
for col in columnes_check:
    print(f"--- Valors únics a la columna: {col} ---")
    print(df[col].value_counts(dropna=False)) # dropna=False per veure també quants nuls hi ha
    print("\n")

--- Valors únics a la columna: gender ---
gender
NaN       3054
F          457
M          413
Male        39
female      28
Femal       17
Name: count, dtype: int64


--- Valors únics a la columna: state ---
state
NaN           2937
Oregon         320
California     211
Arizona        186
Cali           120
Nevada          98
Washington      81
WA              30
AZ              25
Name: count, dtype: int64


--- Valors únics a la columna: education ---
education
NaN                     2937
Bachelor                 324
College                  313
High School or Below     296
Master                    94
Doctor                    37
Bachelors                  7
Name: count, dtype: int64


--- Valors únics a la columna: vehicle_class ---
vehicle_class
NaN              2937
Four-Door Car     576
Two-Door Car      205
SUV               199
Sports Car         57
Luxury SUV         20
Luxury Car         14
Name: count, dtype: int64


--- Valors únics a la columna: customer_lifetime_value ---
customer_lifetime_value
NaN            2940
445811.34%        4
251459.20%        4
2412750.40%       3
684615.03%        3
               ...
1210120.88%       1
245357.08%        1
507566.27%        1
321497.94%        1
899704.02%        1
Name: count, Length: 1028, dtype: int64

In [26]:
gender_map = {
    "Male": "M",
    "female": "F",
    "Femal": "F",
    "F": "F",
    "M": "M"
}
df['gender'] = df['gender'].replace(gender_map)

state_map = {
    "Cali": "California",
    "WA": "Washington",
    "AZ": "Arizona"
}
df['state'] = df['state'].replace(state_map)

df['education'] = df['education'].replace("Bachelors", "Bachelor")

luxury_map = {
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
}
df['vehicle_class'] = df['vehicle_class'].replace(luxury_map)

df['customer_lifetime_value'] = df['customer_lifetime_value'].str.replace('%', '')
df['customer_lifetime_value'] = pd.to_numeric(df['customer_lifetime_value'], errors='coerce')

print("Gender:", df['gender'].unique())
print("State:", df['state'].unique())
print("Vehicle Class:", df['vehicle_class'].unique())
print("Tipus CLV:", df['customer_lifetime_value'].dtype)

Gender: [nan 'F' 'M']
State: ['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' nan]
Vehicle Class: ['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury' nan]
Tipus CLV: float64

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [27]:
# Your code 

df['customer_lifetime_value'] = pd.to_numeric(df['customer_lifetime_value'], errors='coerce')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   object
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(4), object(7)
memory usage: 344.6+ KB

In [29]:
df['number_of_open_complaints'] = df['number_of_open_complaints'].apply(lambda x: x.split('/')[1] if isinstance(x, str) else x)
df['number_of_open_complaints'] = pd.to_numeric(df['number_of_open_complaints'], errors='coerce')

In [31]:
print(df[['customer_lifetime_value', 'number_of_open_complaints']].dtypes)

customer_lifetime_value      float64
number_of_open_complaints    float64
dtype: object

In [30]:
print(df['number_of_open_complaints'].unique())

[ 0.  2.  1.  3.  5.  4. nan]

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [32]:
# Your code here
nuls_per_columna = df.isnull().sum()
print(nuls_per_columna)

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [33]:
df = df.dropna(subset=['customer'])

In [34]:
numeric_cols = df.select_dtypes(include=['number']).columns
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())

In [35]:
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df[col] = df[col].fillna('Unknown')

In [36]:
for col in numeric_cols:
    df[col] = df[col].astype(int)

In [37]:
print("Nuls after cleaning:")
print(df.isnull().sum().sum()) # Hauria de donar 0
print("\nData types after change:")
print(df.dtypes)

Nuls after cleaning:
0

Data types after change:
customer                     object
state                        object
gender                       object
education                    object
customer_lifetime_value       int64
income                        int64
monthly_premium_auto          int64
number_of_open_complaints     int64
policy_type                  object
vehicle_class                object
total_claim_amount            int64
dtype: object

In [38]:
df.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [ ]:
# used dropna for the 'customer' because it has null values and without the costumer i wasnt interested on the rest of the information.  And used fillna for the numerical values because they still make sense using the mean. The final check confirms that there are no more null values and that the data types are as expected.

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [39]:
# Your code here
num_duplicates = df.duplicated().sum()
print(f"WE found {num_duplicates} files duplicate.")

WE found 0 files duplicate.

In [43]:
df = df.drop_duplicates(keep='first')

In [41]:
df = df.drop_duplicates()

In [42]:
df = df.reset_index(drop=True)

In [44]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1066    False
1067    False
1068    False
1069    False
1070    False
Length: 1071, dtype: bool

In [ ]:
#"We used keep='first' to retain the original record and discard any subsequent identical clones as redundant. This ensures data uniqueness while maintaining the chronological integrity of the first entry captured."

In [40]:
df.to_csv('customer_analysis_cleaned.csv', index=False)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [45]:
# Enable autoreload to automatically sync changes from the data_cleaning.py file
%load_ext autoreload
%autoreload 2

# Import the data cleaning module
from data_cleaning import run_pipeline

# Execute the pipeline with the CSV URL
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df_cleaned = run_pipeline(url)

# Display information about the cleaned dataset
print("Dataset shape:", df_cleaned.shape)
print("\nColumn names and types:")
print(df_cleaned.dtypes)
print("\nFirst few rows:")
print(df_cleaned.head())
print("\nData quality summary:")
print(f"Null values remaining: {df_cleaned.isnull().sum().sum()}")
print(f"Duplicate rows remaining: {df_cleaned.duplicated().sum()}")

# Save the cleaned dataset
df_cleaned.to_csv('customer_analysis_cleaned.csv', index=False)
print("\nCleaned dataset saved to 'customer_analysis_cleaned.csv'")

Dataset shape: (1071, 11)

Column names and types:
customer                     object
state                        object
gender                       object
education                    object
customer_lifetime_value       int64
income                        int64
monthly_premium_auto          int64
number_of_open_complaints     int64
policy_type                  object
vehicle_class                object
total_claim_amount            int64
dtype: object

First few rows:
  customer       state   gender             education  \
0  RB50392  Washington  Unknown                Master
1  QZ44356     Arizona        F              Bachelor
2  AI49188      Nevada        F              Bachelor
3  WW63253  California        M              Bachelor
4  GA49547  Washington        M  High School or Below

   customer_lifetime_value  income  monthly_premium_auto  \
0                   793690       0                  1000
1                   697953       0                    94
2                  1288743   48767                   108
3                   764586       0                   106
4                   536307   36357                    68

   number_of_open_complaints     policy_type  vehicle_class  \
0                          0   Personal Auto  Four-Door Car
1                          0   Personal Auto  Four-Door Car
2                          0   Personal Auto   Two-Door Car
3                          0  Corporate Auto            SUV
4                          0   Personal Auto  Four-Door Car

   total_claim_amount
0                   2
1                1131
2                 566
3                 529
4                  17

Data quality summary:
Null values remaining: 0
Duplicate rows remaining: 0

Cleaned dataset saved to 'customer_analysis_cleaned.csv'

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [46]:
# Your code here
display(df_cleaned[['total_claim_amount', 'customer_lifetime_value']].describe())

       total_claim_amount  customer_lifetime_value
count         1071.000000             1.071000e+03
mean           404.528478             7.936898e+05
std            293.041850             6.425757e+05
min              0.000000             2.004350e+05
25%            201.500000             4.048530e+05
50%            354.000000             5.887180e+05
75%            532.000000             8.945205e+05
max           2893.000000             5.816655e+06

In [48]:
high_claim_threshold = df_cleaned['total_claim_amount'].quantile(0.75)
low_clv_threshold = df_cleaned['customer_lifetime_value'].quantile(0.25)

In [49]:
print(f"\nThreshold for High Claim (75th percentile): {high_claim_threshold}")
print(f"Threshold for Low CLV (25th percentile): {low_clv_threshold}")

Threshold for High Claim (75th percentile): 532.0
Threshold for Low CLV (25th percentile): 404853.0

In [51]:
high_risk_customers = df_cleaned[
    (df_cleaned['total_claim_amount'] > high_claim_threshold) & 
    (df_cleaned['customer_lifetime_value'] < low_clv_threshold)]

In [52]:
analysis_summary = high_risk_customers[['total_claim_amount', 'customer_lifetime_value']].describe()
display(analysis_summary)

       total_claim_amount  customer_lifetime_value
count           40.000000                40.000000
mean           723.300000            341577.425000
std            149.216449             56921.466178
min            537.000000            228759.000000
25%            632.750000            304220.500000
50%            685.000000            365995.000000
75%            799.000000            387364.000000
max           1185.000000            402381.000000

In [53]:
print(f"\nNumber of customers identified: {len(high_risk_customers)}")

Number of customers identified: 40